### ISSUE TITLE
[Bug]: Error contacting Renogy API: list index out of range

### ISSUE THREAD

**Issue by codefendant** [firstof9/py-renogy#3]
### The problem

Get this error, log error listed in log section:

![Screenshot_17-12-2024_23710_192 168 0 22](https://github.com/user-attachments/assets/79e9cbb3-1dfd-4c73-8163-4f9db2909920)

### What version of Home Assistant?

2024.12.4

### What version of Renogy?

N/A

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: custom_components.renogy.config_flow
Source: custom_components/renogy/config_flow.py:45
integration: renogy (documentation, issues)
First occurred: 10:56:06 PM (1 occurrences)
Last logged: 10:56:06 PM

Error contacting Renogy API: list index out of range
Traceback (most recent call last):
  File "/config/custom_components/renogy/config_flow.py", line 45, in async_step_user
    await renogy.get_devices()
  File "/usr/local/lib/python3.13/site-packages/renogyapi/__init__.py", line 119, in get_devices
    if "deviceId" in response[0].keys():
                     ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by firstof9** [comment]
Either the API format has changed or you don't have any devices returned by the API.
I'll need to throw in some error handling here.

**Comment by firstof9** [comment]
@codefendant please add the following to your `configuration.yaml` for Home Assistant:

```yaml
logger:
  logs:
    renogyapi: debug
```

Then try the setup once more, this will output debug messages into `home-assistant.log`, I'll need those debug outputs to figure out what's going on.

Thanks.
